/* Checksum.ai autogenerated test */
import { test as base, expect } from "@playwright/test";
import { init, IChecksumPage } from "@checksum-ai/runtime";

const { test, defineChecksumTest, login } = init(base);

test.describe("productListOrNew", () => {
  test.beforeEach(async ({ page }: { page: IChecksumPage }) => {
    await login(page);
    await page.goto("/a/products", { waitUntil: "domcontentloaded" });
  });

  test(
    defineChecksumTest("Unpublish a published product", "pbtWd"),
    async ({ page }) => {
      await page
        .checksumSelector("UNoCk")
        .checksumAI(
          "Click on the menu button of the first published product to access additional options."
        )
        .locator('tr:nth-child(2) > td:nth-child(7) > div')
        .click();
      //   await expect(page.getByText("Edit").first()).toBeVisible();
      //   await expect(page.getByText("Unpublish").first()).toBeVisible();
      await page
        .checksumSelector("gqlau")
        .checksumAI("Click the 'Unpublish' option from the dropdown menu.")
        .getByRole("button", { name: "Unpublish" })
        .click();
      //   await expect(page.getByText("Edit").first()).not.toBeVisible();
      //   await expect(page.getByText("Unpublish").first()).not.toBeVisible();
      //   await expect(page.getByText("Draft").first()).toBeVisible();
      await page
        .checksumSelector("bibWV")
        .checksumAI(
          "Click the 'Unpublished' filter to verify the product status."
        )
        .getByRole("button", { name: "Unpublished" })
        .click();
      //   await expect(page.getByText("1").first()).toBeVisible();
      //   await expect(page).toHaveURL(/\/a\/products\/?(\?.*)?(\#.*)?$/);
      //   await expect(
      //     page.getByText("Eau De Perfume Spray").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Oil Free Moisturizer 100ml").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Freckle Treatment Cream- 15gm").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("- Daal Masoor 500 grams").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Elbow Macaroni - 400 gm").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Orange Essence Food Flavou").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("cereals muesli fruit nuts").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Gulab Powder 50 Gram").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Plant Hanger For Home").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Flying Wooden Bird").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("3D Embellishment Art Lamp").first()
      //   ).not.toBeVisible();
      //   await expect(
      //     page.getByText("Handcraft Chinese style").first()
      //   ).not.toBeVisible();
      //   await expect(page.getByText("Key Holder").first()).not.toBeVisible();
      //   await expect(
      //     page.getByText("Hyaluronic Acid Serum").first()
      //   ).toBeVisible();
      //   await expect(page.getByText("1 of 1").first()).toBeVisible();
    }
  );
});
